package com.lemuridaelabs.honeymcp.modules.archives.api;

import com.lemuridaelabs.honeymcp.modules.archives.service.ArchiveCacheService;
import com.lemuridaelabs.honeymcp.modules.events.dto.HoneyEventType;
import com.lemuridaelabs.honeymcp.modules.events.service.EventLoggingService;
import com.lemuridaelabs.honeymcp.utils.RequestUtils;
import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST API controller for serving synthetic archive files.
 *
 * <p>This controller handles file download requests for generated archive files.
 * Each file access is logged as a high-severity event since it indicates an attacker
 * attempting to exfiltrate data from the honeypot.</p>
 *
 * <p>Files are served with realistic HTTP headers but contain no actual content,
 * as they are synthetic records generated by the AI.</p>
 *
 * @see ArchiveCacheService
 * @see EventLoggingService
 * @since 1.0
 */
@RequiredArgsConstructor
@RestController
@RequestMapping("${honeymcp.server.file-base}")
@Slf4j
public class ArchiveFileApiService {

    private final EventLoggingService eventLoggingService;

    private final ArchiveCacheService archiveCacheService;

    /**
     * Retrieves a file by its unique identifier and returns it as a response entity.
     * If the file is found, it is returned as a binary stream with appropriate headers.
     * If not found, it returns a 404 Not Found response.
     *
     * @param id the unique identifier of the file to retrieve
     * @return a ResponseEntity containing the file as a byte array if found, or a 404 Not Found response if not
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<byte[]> getFile(HttpServletRequest request,
                                          @PathVariable String id) {

        log.info("Getting file with id={}.", id);

        eventLoggingService.highEvent(
                RequestUtils.getEffectiveRemoteIp(request),
                request.getRequestURI(), HoneyEventType.API,
                false,
                String.format("Attempted File Data Retrieval for id=%s", id), null);

        var archiveFileWrapper = archiveCacheService.getArchiveFileRecord(id);

        if (archiveFileWrapper == null) {
            log.warn("No file found for request, id={}.", id);
            return ResponseEntity.notFound().build();
        }

        var archiveFile = archiveFileWrapper.getFile();

        log.info("Found an Archive File Wrapper for request, id={}, archiveFile={}.", id, archiveFile);

        // Set response headers to look realistic
        var headers = new HttpHeaders();
        headers.add(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" +
                archiveFile.getName() + "\"");
        headers.setContentType(MediaType.APPLICATION_OCTET_STREAM);
        var payload = new byte[0];
        headers.setContentLength(payload.length);

        return ResponseEntity.ok()
                .headers(headers)
                .body(payload);
    }

}
